Repository TheWorldAvatar/viz, pull requests merged in 2025-06, with the labels that each got.

#207 PDochev/206/hamburger-menu
  CHANGELOG.md
  VERSION
  code/package.json
  code/src/app/[lang]/@modal/(.)add/[type]/page.tsx
  code/src/app/[lang]/@modal/(.)delete/[type]/[id]/page.tsx
  code/src/app/[lang]/@modal/(.)edit/[type]/[id]/page.tsx
  code/src/app/[lang]/@modal/(.)view/[type]/[id]/page.tsx
  code/src/app/[lang]/add/[type]/page.tsx
  code/src/app/[lang]/analytics/page.tsx
  code/src/app/[lang]/delete/[type]/[id]/page.tsx
  code/src/app/[lang]/edit/[type]/[id]/page.tsx
  code/src/app/[lang]/help/page.tsx
  code/src/app/[lang]/layout.tsx
  code/src/app/[lang]/map/page.tsx
  code/src/app/[lang]/registry/[type]/page.tsx
  code/src/app/[lang]/registry/active/[type]/page.tsx
  code/src/app/[lang]/registry/archive/[type]/page.tsx
  code/src/app/[lang]/registry/pending/[type]/page.tsx
  code/src/app/[lang]/registry/report/[type]/page.tsx
  code/src/app/[lang]/registry/task/date/page.tsx
  code/src/app/[lang]/view/[type]/[id]/page.tsx
  code/src/hooks/float/usePopover.tsx
  code/src/types/settings.ts
  code/src/ui/css/globals.css
  code/src/ui/global-container.tsx
  code/src/ui/interaction/action/popover/popover-button.tsx
  code/src/ui/interaction/auth/keycloak-user-button.module.css
  code/src/ui/interaction/auth/keycloak-user-button.tsx
  code/src/ui/interaction/header/headerbar.tsx
  code/src/ui/navigation/navbar/nav-menu.tsx
  code/src/ui/navigation/navbar/nav.menu.module.css
  code/src/ui/navigation/navbar/navbar-item.tsx
  code/src/ui/pages/landing.tsx
  code/src/ui/text/footer.tsx
  code/src/utils/dictionary/data/de.json
  code/src/utils/dictionary/data/en.json
  docker-compose.yml
Labels: enhancement

#224 Qhouyee/223/buggy registry nav buttons
  CHANGELOG.md
  VERSION
  code/package.json
  code/src/app/[lang]/registry/[type]/page.tsx
  code/src/types/settings.ts
  code/src/types/ui-settings.schema.json
  code/src/ui/navigation/navbar/nav-menu.tsx
  doc/config.md
  docker-compose.yml
Labels: bug

#225 PDochev/222/complete button from table
  CHANGELOG.md
  VERSION
  code/package.json
  code/src/types/form.ts
  code/src/ui/graphic/table/registry/actions/registry-table-action.tsx
  code/src/ui/graphic/table/registry/registry.table.module.css
  code/src/ui/interaction/button.tsx
  code/src/ui/interaction/form/form-container.tsx
  code/src/ui/interaction/form/form.tsx
  code/src/ui/interaction/modal/task/task-modal.tsx
  docker-compose.yml
Labels: enhancement

#234 View and Add buttons german translation
  CHANGELOG.md
  VERSION
  code/package.json
  code/src/ui/interaction/form/field/form-input-container.tsx
  docker-compose.yml
Labels: enhancement

#235 Footer position and layout issues
  CHANGELOG.md
  VERSION
  code/package.json
  code/src/ui/css/globals.css
  code/src/ui/global-container.tsx
  code/src/ui/graphic/table/registry/registry-table-component.tsx
  code/src/ui/interaction/form/field/form-checkbox-field.tsx
  code/src/ui/interaction/form/field/form-input-container.tsx
  code/src/ui/interaction/form/form-container.tsx
  code/src/ui/interaction/form/section/form-schedule.tsx
  code/src/ui/interaction/modal/file/file-modal.tsx
  code/src/ui/interaction/modal/modal.tsx
  code/src/ui/interaction/modal/task/task-modal.tsx
  code/src/ui/pages/landing.tsx
  code/src/ui/pages/static-content-page.tsx
  code/src/ui/text/accordion/accordion-field.tsx
  code/src/ui/text/footer.tsx
  code/src/utils/dictionary/data/de.json
  code/src/utils/dictionary/data/en.json
  docker-compose.yml
Labels: bug, enhancement
