Repository TheWorldAvatar/viz, pull requests merged in 2025-09, with the labels that each got.

#302 Default values Change
  CHANGELOG.md
  VERSION
  code/package.json
  code/src/ui/interaction/form/form-utils.ts
  code/src/ui/interaction/form/section/form-schedule.tsx
  docker-compose.yml
Labels: enhancement

#316 qhouyee/315/optional-geocoding-shapes
  CHANGELOG.md
  VERSION
  code/package.json
  code/src/hooks/geocode/useGeocodeTemplate.tsx
  docker-compose.yml
Labels: bug

#320 Qhouyee/319/add date range selection modal for file downloads
  CHANGELOG.md
  VERSION
  code/package.json
  code/src/ui/graphic/table/registry/registry-table-component.tsx
  code/src/ui/graphic/table/registry/registry-table-utils.tsx
  code/src/ui/graphic/table/registry/ribbon/table-ribbon.tsx
  code/src/ui/interaction/action/file/file-input.tsx
  code/src/ui/interaction/button.tsx
  code/src/ui/interaction/input/date-range.tsx
  code/src/ui/interaction/modal/file/file-modal.tsx
  code/src/ui/navigation/navbar/nav-menu.tsx
  code/src/ui/navigation/navbar/navbar-item.tsx
  code/src/utils/client-utils.ts
  code/src/utils/dictionary/data/de.json
  code/src/utils/dictionary/data/en.json
  doc/config.md
  docker-compose.yml
Labels: enhancement

#310 Accordion component for View routes
  CHANGELOG.md
  VERSION
  code/package.json
  code/src/hooks/form/useFormQuickView.tsx
  code/src/types/form.ts
  code/src/ui/graphic/loader/spinner.tsx
  code/src/ui/interaction/accordion/field/form-quick-view-expandable.tsx
  code/src/ui/interaction/accordion/field/form-quick-view-fields.tsx
  code/src/ui/interaction/accordion/field/form-quick-view-map.tsx
  code/src/ui/interaction/accordion/form-quick-view-body.tsx
  code/src/ui/interaction/accordion/form-quick-view-header.tsx
  code/src/ui/interaction/button.tsx
  code/src/ui/interaction/form/field/field.module.css
  code/src/ui/interaction/form/field/form-input-container.tsx
  code/src/ui/interaction/form/field/input/form-selector.tsx
  code/src/ui/interaction/form/form-container.tsx
  code/src/ui/interaction/form/form-utils.ts
  code/src/ui/interaction/form/section/dependent-form-section.tsx
  code/src/ui/interaction/form/section/form-geocoder.tsx
  code/src/ui/interaction/input/date-range.tsx
  code/src/ui/interaction/modal/task/task-modal.tsx
  code/src/ui/map/geocode/geocode-map-container.tsx
  code/src/ui/map/mapbox/mapbox-container.tsx
  code/src/ui/text/accordion/accordion-field.tsx
  code/src/ui/text/accordion/accordion.tsx
  code/src/ui/text/field/field.tsx
  code/src/utils/client-utils.ts
  code/src/utils/dictionary/data/de.json
  code/src/utils/dictionary/data/en.json
  docker-compose.yml
Labels: enhancement

#358 Changed the onGeocoding click event not to require a validation to pass
  CHANGELOG.md
  VERSION
  code/package.json
  code/src/ui/interaction/form/section/form-geocoder.tsx
  docker-compose.yml
Labels: bug fix
