Repository TheWorldAvatar/viz, pull requests merged in 2025-07, with the labels that each got.

#240 Improved the size of the actions buttons and removed the tooltips for…
  CHANGELOG.md
  VERSION
  code/package.json
  code/src/ui/graphic/table/registry/actions/registry-table-action.tsx
  docker-compose.yml
Labels: enhancement

#244 Added new route (Registry Submission) from which you can add a new jo…
  CHANGELOG.md
  VERSION
  code/package.json
  code/pnpm-lock.yaml
  code/src/app/[lang]/layout.tsx
  code/src/ui/global-container.tsx
  code/src/ui/graphic/table/registry/actions/registry-table-action.tsx
  code/src/ui/graphic/table/registry/registry-table-component.tsx
  code/src/ui/graphic/table/registry/ribbon/table-ribbon.tsx
  code/src/ui/interaction/action/toast/toast.tsx
  code/src/ui/interaction/form/form-container.tsx
  code/src/ui/interaction/form/form.tsx
  code/src/ui/interaction/header/headerbar.tsx
  code/src/ui/interaction/modal/file/file-modal.tsx
  code/src/ui/interaction/modal/modal.tsx
  code/src/ui/interaction/modal/search/search-modal.tsx
  code/src/ui/interaction/modal/task/task-modal.tsx
  code/src/ui/map/map-helper.ts
  code/src/ui/navigation/navbar/nav-menu.tsx
  code/src/ui/navigation/return/return.module.css
  code/src/ui/navigation/return/return.tsx
  code/src/ui/text/response/response.tsx
  code/src/utils/auth/session-utils.ts
  code/src/utils/dictionary/data/de.json
  code/src/utils/dictionary/data/en.json
  doc/config.md
  docker-compose.yml
Labels: enhancement, dependencies

#262 Production Api Logs
  CHANGELOG.md
  VERSION
  code/package.json
  code/src/app/api/registry/[slug]/route.ts
  docker-compose.yml
Labels: bug

#266 Fixed the Date conversion method from toISOString to toLocaleDateString
  CHANGELOG.md
  VERSION
  code/package.json
  code/src/ui/graphic/table/registry/registry-table-component.tsx
  code/src/ui/graphic/table/registry/ribbon/table-ribbon.tsx
  code/src/ui/interaction/input/date-range.tsx
  docker-compose.yml
Labels: bug

#265 Toast translations
  CHANGELOG.md
  README.md
  VERSION
  code/package.json
  code/src/app/api/registry/[slug]/route.ts
  code/src/ui/graphic/table/registry/registry-table-component.tsx
  code/src/utils/dictionary/data/de.json
  docker-compose.yml
Labels: bug, enhancement
